# Docker Kuma

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Only needed if you are monitoring other docker contianers
      - './uptimekuma_data:/app/data'  # store data during updates
    ports:
      - 3001:3001 # <host>:<container>
    restart: always
